apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-projeto
  labels:
    app: scc-projeto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scc-projeto
  template:
    metadata:
      labels:
        app: scc-projeto
    spec:
      containers:
      - name: scc-projeto
        image: sccprojeto/scc_projeto:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80