apiVersion: v1
kind: Service
metadata:
  name: scc-projeto
  labels:
    app: scc-projeto
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: scc-projeto
  sessionAffinity: None