apiVersion: v1
kind: Service
metadata:
  name: scc-projeto-auth
  labels:
    app: scc-projeto-auth
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9999
  selector:
    app: scc-projeto-auth
  sessionAffinity: None
